name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile software
        run: gcc -o bloom petlinux/main.c
      
      - name: Run program
        run: ./bloom